server.port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: service-users
          uri: lb://service-users
          predicates:
            - Path=/api/users/**,/oauth2/**,/connect/*,/login,/userinfo
        - id: client-web-spa
          uri: http://client:80
          predicates:
            - Path=/**
